name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: |
          if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
            npm run build:win
          elif [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
            npm run build:mac
          else
            npm run build:linux
          fi
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release
          path: dist
